# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval: 50
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: uer

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: wrd

dataset:
  num_workers: 6
  max_tokens: 1280000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 10000
  validate_interval: 50
  valid_subset: valid

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 20000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: contentvec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  # mask_channel_prob: 0.5
  # mask_channel_length: 64
  # layerdrop: 0.05
  # activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000

  skip_masked: false
  skip_nomask: false
  extractor_mode: default
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  untie_final_proj: true
  encoder_layers_1: 1
  logit_temp_ctr: 1
  ctr_layers: [-1]
  target_layer: 5
