# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval: 50
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: uer

task:
  _name: audio_mean_teacher
  data: ???
  normalize: false
  labels: wrd
  trans_path: ???

dataset:
  num_workers: 8
  max_tokens: 3200000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 0
  validate_interval: 50
  valid_subset: valid

criterion:
  _name: semi_supervised_ctc
  zero_infinity: true
  alpha: 0.001

optimization:
  max_update: 20000
  lr: [0.000005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.3, 0.2, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc_mean_teacher
  is_from_finetune: true
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.05
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 500
  ema_decay: 0.1
  ema_end_decay: 0.999
